version: '3.8'

services:
  redis:
    image: redis/redis-stack:7.4.0-v3
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  ollama:
    image: ollama/ollama:0.6.8
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
  redis-data: